[2024-11-06T07:42:58.048+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T07:42:58.222+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-06T06:42:05.001646+00:00 [queued]>
[2024-11-06T07:42:58.230+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-06T06:42:05.001646+00:00 [queued]>
[2024-11-06T07:42:58.230+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-06T07:42:58.243+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.insert_into_cpu_specs_table_sql> on 2024-11-06 06:42:05.001646+00:00
[2024-11-06T07:42:58.247+0000] {standard_task_runner.py:72} INFO - Started process 61372 to run task
[2024-11-06T07:42:58.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'database_tasks.insert_into_cpu_specs_table_sql', 'manual__2024-11-06T06:42:05.001646+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpgoqliy4v']
[2024-11-06T07:42:58.253+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask database_tasks.insert_into_cpu_specs_table_sql
[2024-11-06T07:42:58.317+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-06T06:42:05.001646+00:00 [running]> on host 9694314923d2
[2024-11-06T07:42:58.413+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='database_tasks.insert_into_cpu_specs_table_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T06:42:05.001646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T06:42:05.001646+00:00'
[2024-11-06T07:42:58.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T07:42:58.437+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/airflow/dags/database/sql_helper.py", line 242, in get_insert_into_cpu_specs_table_sql
    insert_command = f"""
                     ^^^^
ValueError: Invalid format specifier ' 'gearvn', 'brand': 'msi', 'name': 'msi modern 15 f13mg 082vn', 'cpu': 'intel core i5-1335u', 'vga': 'n/a', 'ram_amount': 16, 'ram_type': 'ddr4', 'storage_amount': 512, 'storage_type': 'ssd', 'webcam_resolution': 'hd', 'screen_size': 15.6, 'screen_resolution': '1920x1080', 'screen_refresh_rate': 60, 'screen_brightness': 'n/a', 'battery_capacity': 46.8, 'battery_cells': 3, 'weight': 1.7, 'default_os': 'windows 11 home', 'warranty': 24, 'price': 16490000, 'width': 35.89, 'depth': 23.59, 'height': 1.99, 'number_usb_a_ports': 3, 'number_usb_c_ports': 1, 'number_hdmi_ports': 1, 'number_ethernet_ports': 0, 'number_audio_jacks': 1' for object of type 'str'
[2024-11-06T07:42:58.452+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=main_dag, task_id=database_tasks.insert_into_cpu_specs_table_sql, run_id=manual__2024-11-06T06:42:05.001646+00:00, execution_date=20241106T064205, start_date=20241106T074258, end_date=20241106T074258
[2024-11-06T07:42:58.471+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T07:42:58.472+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task database_tasks.insert_into_cpu_specs_table_sql (Invalid format specifier ' 'gearvn', 'brand': 'msi', 'name': 'msi modern 15 f13mg 082vn', 'cpu': 'intel core i5-1335u', 'vga': 'n/a', 'ram_amount': 16, 'ram_type': 'ddr4', 'storage_amount': 512, 'storage_type': 'ssd', 'webcam_resolution': 'hd', 'screen_size': 15.6, 'screen_resolution': '1920x1080', 'screen_refresh_rate': 60, 'screen_brightness': 'n/a', 'battery_capacity': 46.8, 'battery_cells': 3, 'weight': 1.7, 'default_os': 'windows 11 home', 'warranty': 24, 'price': 16490000, 'width': 35.89, 'depth': 23.59, 'height': 1.99, 'number_usb_a_ports': 3, 'number_usb_c_ports': 1, 'number_hdmi_ports': 1, 'number_ethernet_ports': 0, 'number_audio_jacks': 1' for object of type 'str'; 61372)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/airflow/dags/database/sql_helper.py", line 242, in get_insert_into_cpu_specs_table_sql
    insert_command = f"""
                     ^^^^
ValueError: Invalid format specifier ' 'gearvn', 'brand': 'msi', 'name': 'msi modern 15 f13mg 082vn', 'cpu': 'intel core i5-1335u', 'vga': 'n/a', 'ram_amount': 16, 'ram_type': 'ddr4', 'storage_amount': 512, 'storage_type': 'ssd', 'webcam_resolution': 'hd', 'screen_size': 15.6, 'screen_resolution': '1920x1080', 'screen_refresh_rate': 60, 'screen_brightness': 'n/a', 'battery_capacity': 46.8, 'battery_cells': 3, 'weight': 1.7, 'default_os': 'windows 11 home', 'warranty': 24, 'price': 16490000, 'width': 35.89, 'depth': 23.59, 'height': 1.99, 'number_usb_a_ports': 3, 'number_usb_c_ports': 1, 'number_hdmi_ports': 1, 'number_ethernet_ports': 0, 'number_audio_jacks': 1' for object of type 'str'
[2024-11-06T07:42:58.512+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T07:42:58.531+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.11/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-11-06T07:42:58.545+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T07:42:58.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
