[2024-11-19T17:15:27.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T17:15:27.798+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_gearvn manual__2024-11-19T17:15:06.654443+00:00 [queued]>
[2024-11-19T17:15:27.810+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_gearvn manual__2024-11-19T17:15:06.654443+00:00 [queued]>
[2024-11-19T17:15:27.810+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-19T17:15:27.835+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): laptop_scraping_tasks.scrape_gearvn> on 2024-11-19 17:15:06.654443+00:00
[2024-11-19T17:15:27.840+0000] {standard_task_runner.py:72} INFO - Started process 4782 to run task
[2024-11-19T17:15:27.843+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'laptop_scraping_tasks.scrape_gearvn', 'manual__2024-11-19T17:15:06.654443+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpy0m92btp']
[2024-11-19T17:15:27.844+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask laptop_scraping_tasks.scrape_gearvn
[2024-11-19T17:15:27.908+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.laptop_scraping_tasks.scrape_gearvn manual__2024-11-19T17:15:06.654443+00:00 [running]> on host 12fcc3f4650c
[2024-11-19T17:15:28.007+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='laptop_scraping_tasks.scrape_gearvn' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T17:15:06.654443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T17:15:06.654443+00:00'
[2024-11-19T17:15:28.008+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T17:15:28.020+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-19T17:15:28.020+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl gearvn_spider -O ../temp/gearvn_data.json']
[2024-11-19T17:15:28.028+0000] {subprocess.py:86} INFO - Output:
[2024-11-19T17:15:43.030+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-19T17:15:43.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-19T17:15:43.039+0000] {process_utils.py:132} INFO - Sending 15 to group 4782. PIDs of all processes in the group: [4791, 4793, 4801, 5019, 5038, 5074, 5137, 5145, 5149, 5163, 5272, 5600, 5602, 5799, 5877, 5881, 4782]
[2024-11-19T17:15:43.040+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 4782
[2024-11-19T17:15:43.041+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-19T17:15:43.042+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-19T17:15:43.074+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5038, status='terminated', started='17:15:28') (5038) terminated with exit code None
[2024-11-19T17:15:43.075+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5600, status='terminated', started='17:15:34') (5600) terminated with exit code None
[2024-11-19T17:15:43.076+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5149, status='terminated', started='17:15:30') (5149) terminated with exit code None
[2024-11-19T17:15:43.077+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-19T17:15:43.084+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=laptop_scraping_tasks.scrape_gearvn, run_id=manual__2024-11-19T17:15:06.654443+00:00, execution_date=20241119T171506, start_date=20241119T171527, end_date=20241119T171543
[2024-11-19T17:15:43.104+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T17:15:43.133+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4782, status='terminated', exitcode=2, started='17:15:27') (4782) terminated with exit code 2
[2024-11-19T17:15:43.133+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5602, status='terminated', started='17:15:34') (5602) terminated with exit code None
[2024-11-19T17:15:43.134+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5145, status='terminated', started='17:15:30') (5145) terminated with exit code None
[2024-11-19T17:15:43.135+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5799, status='terminated', started='17:15:37') (5799) terminated with exit code None
[2024-11-19T17:15:43.135+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5163, status='terminated', started='17:15:30') (5163) terminated with exit code None
[2024-11-19T17:15:43.136+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5272, status='terminated', started='17:15:32') (5272) terminated with exit code None
[2024-11-19T17:15:43.233+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5137, status='terminated', started='17:15:29') (5137) terminated with exit code None
[2024-11-19T17:15:43.233+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5074, status='terminated', started='17:15:29') (5074) terminated with exit code None
[2024-11-19T17:15:43.234+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5877, status='terminated', started='17:15:38') (5877) terminated with exit code None
[2024-11-19T17:15:43.332+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5019, status='terminated', started='17:15:28') (5019) terminated with exit code None
[2024-11-19T17:15:43.333+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5881, status='terminated', started='17:15:38') (5881) terminated with exit code None
[2024-11-19T17:15:43.333+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4801, status='terminated', started='17:15:28') (4801) terminated with exit code None
[2024-11-19T17:15:44.366+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4793, status='terminated', started='17:15:28') (4793) terminated with exit code None
[2024-11-19T17:15:44.546+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4791, status='terminated', started='17:15:27') (4791) terminated with exit code None
