[2024-11-20T03:29:50.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T03:29:50.712+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_hacom manual__2024-11-20T02:00:30.526702+00:00 [queued]>
[2024-11-20T03:29:50.719+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_hacom manual__2024-11-20T02:00:30.526702+00:00 [queued]>
[2024-11-20T03:29:50.719+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-20T03:29:50.729+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): laptop_scraping_tasks.scrape_hacom> on 2024-11-20 02:00:30.526702+00:00
[2024-11-20T03:29:50.732+0000] {standard_task_runner.py:72} INFO - Started process 15170 to run task
[2024-11-20T03:29:50.735+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'laptop_scraping_tasks.scrape_hacom', 'manual__2024-11-20T02:00:30.526702+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1yigv8xx']
[2024-11-20T03:29:50.736+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask laptop_scraping_tasks.scrape_hacom
[2024-11-20T03:29:50.789+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.laptop_scraping_tasks.scrape_hacom manual__2024-11-20T02:00:30.526702+00:00 [running]> on host 7331716c13db
[2024-11-20T03:29:50.864+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='laptop_scraping_tasks.scrape_hacom' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T02:00:30.526702+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T02:00:30.526702+00:00'
[2024-11-20T03:29:50.865+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T03:29:50.877+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-20T03:29:50.878+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl hacom_spider -O ../temp/hacom_data.json']
[2024-11-20T03:29:50.884+0000] {subprocess.py:86} INFO - Output:
[2024-11-20T03:36:06.006+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-20T03:36:06.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-20T03:36:06.017+0000] {process_utils.py:132} INFO - Sending 15 to group 15170. PIDs of all processes in the group: [15178, 15181, 15189, 15383, 15396, 15432, 15490, 15804, 16266, 16492, 16506, 15170]
[2024-11-20T03:36:06.018+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 15170
[2024-11-20T03:36:06.021+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-20T03:36:06.025+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-20T03:36:06.078+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15189, status='terminated', started='03:29:51') (15189) terminated with exit code None
[2024-11-20T03:36:06.080+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15432, status='terminated', started='03:29:51') (15432) terminated with exit code None
[2024-11-20T03:36:06.081+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=16266, status='terminated', started='03:30:01') (16266) terminated with exit code None
[2024-11-20T03:36:06.077+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-20T03:36:06.093+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=laptop_scraping_tasks.scrape_hacom, run_id=manual__2024-11-20T02:00:30.526702+00:00, execution_date=20241120T020030, start_date=20241120T032950, end_date=20241120T033606
[2024-11-20T03:36:06.123+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T03:36:06.276+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=16506, status='terminated', started='03:30:02') (16506) terminated with exit code None
[2024-11-20T03:36:06.276+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15170, status='terminated', exitcode=2, started='03:29:50') (15170) terminated with exit code 2
[2024-11-20T03:36:06.277+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=16492, status='terminated', started='03:30:02') (16492) terminated with exit code None
[2024-11-20T03:36:06.278+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15383, status='terminated', started='03:29:51') (15383) terminated with exit code None
[2024-11-20T03:36:06.279+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15490, status='terminated', started='03:29:52') (15490) terminated with exit code None
[2024-11-20T03:36:06.279+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15804, status='terminated', started='03:29:55') (15804) terminated with exit code None
[2024-11-20T03:36:06.280+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15396, status='terminated', started='03:29:51') (15396) terminated with exit code None
[2024-11-20T03:36:06.853+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-20T03:36:38.232+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15181, status='terminated', started='03:29:51') (15181) terminated with exit code None
[2024-11-20T03:36:38.263+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15178, status='terminated', started='03:29:50') (15178) terminated with exit code None
