[2024-11-19T17:15:37.221+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T17:15:37.583+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_cellphones manual__2024-11-19T17:15:06.654443+00:00 [queued]>
[2024-11-19T17:15:37.591+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_cellphones manual__2024-11-19T17:15:06.654443+00:00 [queued]>
[2024-11-19T17:15:37.592+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-19T17:15:37.606+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): laptop_scraping_tasks.scrape_cellphones> on 2024-11-19 17:15:06.654443+00:00
[2024-11-19T17:15:37.609+0000] {standard_task_runner.py:72} INFO - Started process 5723 to run task
[2024-11-19T17:15:37.612+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'laptop_scraping_tasks.scrape_cellphones', 'manual__2024-11-19T17:15:06.654443+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmppeyban3w']
[2024-11-19T17:15:37.613+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask laptop_scraping_tasks.scrape_cellphones
[2024-11-19T17:15:37.684+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.laptop_scraping_tasks.scrape_cellphones manual__2024-11-19T17:15:06.654443+00:00 [running]> on host 12fcc3f4650c
[2024-11-19T17:15:37.787+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='laptop_scraping_tasks.scrape_cellphones' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T17:15:06.654443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T17:15:06.654443+00:00'
[2024-11-19T17:15:37.788+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T17:15:37.813+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-19T17:15:37.814+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl cellphones_spider -O ../temp/cellphones_data.json']
[2024-11-19T17:15:37.822+0000] {subprocess.py:86} INFO - Output:
[2024-11-19T17:15:52.816+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-19T17:15:52.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-19T17:15:52.823+0000] {process_utils.py:132} INFO - Sending 15 to group 5723. PIDs of all processes in the group: [5829, 5841, 5850, 5979, 6131, 6164, 6241, 6249, 6268, 6292, 6581, 6700, 6899, 6912, 5723]
[2024-11-19T17:15:52.823+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 5723
[2024-11-19T17:15:52.824+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-19T17:15:52.825+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-19T17:15:52.843+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-19T17:15:52.852+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=laptop_scraping_tasks.scrape_cellphones, run_id=manual__2024-11-19T17:15:06.654443+00:00, execution_date=20241119T171506, start_date=20241119T171537, end_date=20241119T171552
[2024-11-19T17:15:52.867+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T17:15:52.921+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6912, status='terminated', started='17:15:47') (6912) terminated with exit code None
[2024-11-19T17:15:52.922+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5723, status='terminated', exitcode=2, started='17:15:37') (5723) terminated with exit code 2
[2024-11-19T17:15:52.922+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6292, status='terminated', started='17:15:40') (6292) terminated with exit code None
[2024-11-19T17:15:52.923+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6241, status='terminated', started='17:15:39') (6241) terminated with exit code None
[2024-11-19T17:15:52.924+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6268, status='terminated', started='17:15:39') (6268) terminated with exit code None
[2024-11-19T17:15:52.926+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6581, status='terminated', started='17:15:43') (6581) terminated with exit code None
[2024-11-19T17:15:52.927+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6700, status='terminated', started='17:15:45') (6700) terminated with exit code None
[2024-11-19T17:15:52.928+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5850, status='terminated', started='17:15:38') (5850) terminated with exit code None
[2024-11-19T17:15:52.929+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6249, status='terminated', started='17:15:39') (6249) terminated with exit code None
[2024-11-19T17:15:52.929+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6899, status='terminated', started='17:15:47') (6899) terminated with exit code None
[2024-11-19T17:15:52.930+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6131, status='terminated', started='17:15:38') (6131) terminated with exit code None
[2024-11-19T17:15:53.028+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6164, status='terminated', started='17:15:38') (6164) terminated with exit code None
[2024-11-19T17:15:53.028+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5979, status='terminated', started='17:15:38') (5979) terminated with exit code None
[2024-11-19T17:15:54.978+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5841, status='terminated', started='17:15:38') (5841) terminated with exit code None
[2024-11-19T17:15:55.076+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5829, status='terminated', started='17:15:37') (5829) terminated with exit code None
